import React from 'react';
import { Stack, Typography, Grid } from '@mui/material';

const AboutSection = () => {
  return (
    <Stack
      direction='column'
      sx={{
        justifyContent: { xs: null, md: 'center' },
        textAlign: { xs: 'center', md: 'left' },
        marginTop: { xs: '1em', md: 0 },
      }}
      minHeight='80vh'
    >
      <Typography variant='h4'>How does it work?</Typography>
      <Typography variant='subtitle1' gutterBottom>
        We use AI to generate images from text prompts. All the image search
        results you see were generated by Pro users. Sign up for Pro to generate
        your own.
      </Typography>
      <Typography variant='h4'>Are these images truly free?</Typography>
      <Typography variant='subtitle1' gutterBottom>
        Yes! You can use these images for free in any meme, project, etc
        commercial or otherwise! All images generated with our models are being
        put In the public domain.
      </Typography>
      <Grid container direction='row'>
        <Grid item xs={12} md={4}>
          <Typography variant='h4' color='primary'>
            Free Tier
            <br />
            (0$/month)
          </Typography>

          <Typography color='primary'>
            Search the library of user generated photos for free.
          </Typography>

          <Typography color='primary' fontWeight={700} gutterBottom>
            No generation privileges.
          </Typography>
        </Grid>
        <Grid item xs={12} md={4}>
          <Typography variant='h4' color='secondary'>
            Pro Tier
            <br />
            ($5/month)
          </Typography>
          <Typography color='secondary'>
            Search the library of user generated photos for free.
          </Typography>
          <Typography color='secondary' fontWeight={700} gutterBottom>
            Generate 1000 photos/month
          </Typography>
        </Grid>
        <Grid item xs={12} md={4}>
          <Typography variant='h4' color='error'>
            Premium Tier
            <br />
            ($15/month)
          </Typography>
          <Typography color='error'>
            Search the library of user generated photos for free.
          </Typography>
          <Typography color='error' fontWeight={700} gutterBottom>
            Generate unlimited photos
          </Typography>
        </Grid>
      </Grid>
    </Stack>
  );
};

export default AboutSection;
